// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwhutmxhymjwimxeavbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13aHV0bXhoeW1qd2lteGVhdmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NTc1ODMsImV4cCI6MjA3MjUzMzU4M30.j9b9QYOAEFNYZ0YF4tcKNvfa_vJiOVjGVorNa3OjwCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});